# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20160520_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quser',
            name='user',
        ),
        migrations.DeleteModel(
            name='QUser',
        ),
    ]
